# Directories
PROJECT_DIR=$(pwd)
DOCUMENT_ROOT_FOLDER=$PROJECT_DIR"/DOCUMENT_ROOT_FOLDER"
DOWNLOAD_DIR=$PROJECT_DIR"/test/download"

# HTTP Server
HTTP_SERVER_BIN=$PROJECT_DIR"/cmake-build-debug/http_server/http_server"
#"$HTTP_SERVER_BIN" -p $HTTP_SERVER_PORT $DOCUMENT_ROOT_FOLDER &
HTTP_SERVER_PORT=8000
URL="localhost:$HTTP_SERVER_PORT"

# Test Case
RESOURCE="text/Test.txt"
wget -v -O "$DOWNLOAD_DIR/$RESOURCE" "$URL/$RESOURCE"
sha256sum "$DOCUMENT_ROOT_FOLDER/$RESOURCE" "$DOWNLOAD_DIR/$RESOURCE"
diff "$DOCUMENT_ROOT_FOLDER/$RESOURCE" "$DOWNLOAD_DIR/$RESOURCE"

RESOURCE=""
wget -v -O "$DOWNLOAD_DIR/index.html" "$URL/$RESOURCE"
sha256sum "$DOCUMENT_ROOT_FOLDER/index.html" "$DOWNLOAD_DIR/index.html"
diff "$DOCUMENT_ROOT_FOLDER/index.html" "$DOWNLOAD_DIR/index.html"